apiVersion: batch/v1
kind: Job
metadata:
  name: ecr-secret-refresh-once
  namespace: kube-system
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: ecr-refresh
          image: amazon/aws-cli:2.15.0
          command:
            - /bin/sh
            - -c
            - |
              aws ecr get-login-password --region ap-south-1 \
              | kubectl create secret docker-registry ecr-registry-secret \
                  --docker-server=908692150527.dkr.ecr.ap-south-1.amazonaws.com \
                  --docker-username=AWS \
                  --docker-password=$(cat) \
                  --namespace apps \
                  --dry-run=client -o yaml \
              | kubectl apply -f -
