apiVersion: batch/v1
kind: Job
metadata:
  name: ecr-secret-refresh-once
  namespace: kube-system
spec:
  template:
    spec:
      serviceAccountName: default
      restartPolicy: OnFailure
      containers:
      - name: refresh
        image: amazon/aws-cli
        command:
        - /bin/sh
        - -c
        - |
          aws ecr get-login-password --region ap-south-1 | \
          kubectl create secret docker-registry ecr-registry-secret \
            --docker-server=908692150527.dkr.ecr.ap-south-1.amazonaws.com \
            --docker-username=AWS \
            --docker-password-stdin \
            --namespace apps \
            --dry-run=client -o yaml | kubectl apply -f -
