apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-service
  namespace: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/theradheshyampatil/micro-gitops-platform-gitops.git
    targetRevision: main
    path: apps/product-service
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
