apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-refresh-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ecr-refresh-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ecr-refresh-binding
subjects:
- kind: ServiceAccount
  name: ecr-refresh-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: ecr-refresh-role
  apiGroup: rbac.authorization.k8s.io
