apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecr-secret-refresh
  namespace: gitops
spec:
  project: default
  source:
    repoURL: git@github.com:theradheshyampatil/micro-gitops-platform-gitops.git
    targetRevision: main
    path: infra/ecr-secret-refresh
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
